import { Inter } from "next/font/google";
import { UIChakraProvider } from "../providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <UIChakraProvider>
        <body className={inter.className}>{children}</body>
      </UIChakraProvider>
    </html>
  );
}
