import { inter } from "./fonts";
import Link from "next/link";

import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/#hero">Início</Link>
          <Link href="/#about">Sobre mim</Link>
          <Link href="/#services">Serviços</Link>
          <Link href="/#blog">Blog</Link>
          <Link href="/#contact">Contato</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
