import { inter } from "./fonts";
import Link from "next/link";
import { UIChakraProvider } from "./providers";
import {
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuDivider,
} from "@chakra-ui/react";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UIChakraProvider>
        <body className={inter.className}>
          <nav>
            <Link href="/#hero">Início</Link>
            <Link href="/#about">Sobre mim</Link>
            <Menu>
              <MenuButton as={"span"}>Serviços</MenuButton>
              <MenuList>
                <MenuItem>
                  <Link href="/#therapy">Psicoterapia</Link>
                </MenuItem>
                <MenuDivider />
                <MenuItem>
                  <Link href="/academia-emocional">Academia emocional</Link>
                </MenuItem>
              </MenuList>
            </Menu>
            <Link href="/#blog">Blog</Link>
            <Link href="/#faq">FAQ</Link>
            <Link href="/#contact">Contato</Link>
          </nav>
          {children}
        </body>
      </UIChakraProvider>
    </html>
  );
}
